title: Gezinshuis Bodhiboom
slogan: Gezinshuis Bodhiboom, een plek voor ieder kind
author: Sudesh Jethoe

# for github pages
#remote_theme: daattali/beautiful-jekyll@5.0.0
# for local development
theme: beautiful-jekyll-theme

url: https://gezinshuisbodhitree.nl

social-network-links:
  email: "algemeen@gezinshuisbodhitree.nl"

url-pretty: "gezinshuisbodhitree.nl"

# google tag manager id
gtm: "GTM-NXZ4KCG"

navbar-links:
  Over Ons: "over-ons"
  Wat Bieden Wij: "wat-bieden-wij"
  Bronnen:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
      Author's home: "https://deanattali.com"

# logo size: 600x80 px
logo: /assets/images/logo_600x80.jpg


# Theme works best with Kramdown (using the table of contents function)
timezone           : "Europe/Amsterdam"
markdown           : kramdown
permalink          : /:categories/:title/
highlighter        : rouge
excerpt_separator  : "<!--more-->"
include            : ['.htaccess']
# Exclude these files from your production _site
exclude:
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - INSTALL.md
  - vendor

language: nl

# Used › default.html front-matter and compress.html
# # Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

